// src/react/ValueChange.js
import React from 'react'
import cx from 'classnames'
import styles from './ValueChange.module.scss'

const Change = {
  true: ['lima', 'triangle-up'],
  false: ['persimmon', 'triangle-down'],
}

const notChanged = ['texas-rose', 'lock-small']

const ValueChange = ({ className, change, render }) => {
  const [accent, triangle] = change !== 0 ? Change[change > 0] : notChanged

  return (
    <span
      className={cx(styles.change, className)}
      style={{ color: `var(--${accent})`, fill: `var(--${accent})` }}
    >
      {render(Math.abs(change))}
    </span>
  )
}

ValueChange.defaultProps = {
  change: 0,
  render: change => change,
}

export default ValueChange

// src/components/ValueChange.svelte
<script context="module">
  export const percentChange = (change) => `${parseFloat(change).toFixed(2)}%`
</script>

<script>
  let klass = ''
  export { klass as class }
  export let change = 0
  export let formatter = (val) => val

  let res
  $: res = change > 0 ? 'up' : 'down'
</script>

<template lang="pug">
include /ui/mixins

span.change(class='{klass} {res}')
  +icon('triangle-up').triangle
  | {formatter(Math.abs(change))}
</template>

<style lang="scss">
  @import '@/mixins';

  .triangle {
    @include size(6px, 4px);
    margin-right: 6px;
  }

  .change {
    color: var(--texas-rose);
    fill: var(--texas-rose);
  }

  .up {
    color: var(--lima);
    fill: var(--lima);
  }

  .down {
    color: var(--persimmon);
    fill: var(--persimmon);

    .triangle {
      transform: rotate(180deg);
    }
  }
</style>
